name: UDS Stack CI Automation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Environment
      run: |
        python --version
        pip --version
        pip list

    - name: Lint with flake8
      run: |
        # Use python -m to ensure the correct flake8 is used
        python -m pip install flake8
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


    - name: Robot Framework Syntax Check
      run: |
        python -m robot --version
        # REAL RUN on self-hosted hardware
        python -m robot run_uds_test.robot

